# Generated by Django 4.1.2 on 2022-12-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='locations',
            field=models.CharField(default='', max_length=200),
        ),
    ]
