# Generated by Django 4.1.2 on 2022-12-06 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='current_profile_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='coursemodels',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='credit',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='owner_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_owner', to='homepage.profile'),
        ),
    ]
