# Generated by Django 4.1.2 on 2022-12-06 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_remove_coursemodel_current_profile_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursemember',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='coursemember',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursemember',
            name='user',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseMember',
        ),
    ]
