# Generated by Django 4.1.2 on 2022-12-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_coursemember_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='class_num',
            field=models.CharField(default='', max_length=200),
        ),
    ]
